backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/assets
public_folder: /assets
extension: mdx
format: frontmatter
widget: mdx

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
